include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning

  exclude:
    - 'lib/generated/*'

linter:
  rules:
    - prefer_single_quotes
    - library_names
    - directives_ordering
    - lines_longer_than_80_chars
    - public_member_api_docs
    - prefer_relative_imports
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_catching_errors
    - use_to_and_as_if_applicable
    - one_member_abstracts
    - avoid_classes_with_only_static_members
    - prefer_mixin
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_this
    - type_annotate_public_apis
    - omit_local_variable_types
    - avoid_types_on_closure_parameters
    - avoid_private_typedef_functions
    - avoid_positional_boolean_parameters
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_null_checks_in_equality_operators
    - unawaited_futures