name: travelmakerapp
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  path_provider: ^2.1.5
  sqflite: ^2.2.8+4
  google_maps_flutter: ^2.7.0
  flutter_pdfview: ^1.3.2


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  country_flags: ^3.3.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  image_picker: ^1.0.4
  http: ^1.4.0
  flutter_typeahead: ^5.2.0
  pdf: ^3.11.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/fonts/
    - assets/images/Logo1.png
    - assets/images/cello_trips_logo_icon_dark_theme.jpg
    - assets/images/cello_trips_logo_text_dark_theme.jpg
    - assets/images/cello_trips_logo_icon_light_theme.jpg
    - assets/images/cello_trips_logo_text_light_theme.jpg


  fonts:
    - family: AlumniSans
      fonts:
        - asset: assets/fonts/AlumniSans-Regular.ttf
          weight: 700


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
assets/images/cello_trips_logo_icon_dark_theme:
  jpg:
